### ISSUE TITLE
Please  add  more  styles  in  the  Markdown  format.

### ISSUE THREAD

**Issue by bd-dxg** [keksiqc/monospace-theme#1]
I just found this theme in vscode, it's very good.

I often write markdown files in vscode, but idx-monospace-theme doesn't stand out enough for some markdown styles.

For example:

1. The content in backticks should be highlighted
2. Bold text content should be highlighted
3. The keyword of the code block identifying the code language should be highlighted
---

1. ![image](https://github.com/keksiqc/idx-monospace-theme/assets/34816426/f28054cf-5322-4f08-b3af-22d082209bbb)
2. ![image](https://github.com/keksiqc/idx-monospace-theme/assets/34816426/e734a22c-a525-4375-9943-5bded33c8f7b)
3. ![image](https://github.com/keksiqc/idx-monospace-theme/assets/34816426/89fa378f-a522-442c-87b5-255e6dc478fa)

**Comment by keksiqc** [comment]
Great to hear that you like this Theme!
More markdown styles are included in the recently published [v1.1.0](https://github.com/keksiqc/idx-monospace-theme/releases/tag/v1.1.0).
Feel free to open a pull request if you have any changes in mind.
