### ISSUE TITLE
File icon for isml?

### ISSUE THREAD

**Issue by dukio** [keksiqc/monospace-theme#9]
Hi, hopefully this is the right place to ask :crossed_fingers: 

Basically I work a lot with SFCC which uses "[.isml](https://developer.salesforce.com/docs/commerce/b2c-commerce/guide/b2c-isml.html)" template files. The problem is the current icon (which I think is the default icon for unknown files) is very similar to the folders:
![image](https://github.com/keksiqc/monospace-theme/assets/2744227/914e468a-21ba-4bd8-8a31-45323fb553bb)

The shape is different, but the color looks identical... so sometimes it's a bit harder to differentiate files from folders.
Is there any way to customize them? or could you add a custom icon for them?

**Comment by keksiqc** [comment]
I've just integrated ISML into the theme using the XML icon. Now we'll have to wait for the new version to be approved.
